name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install PyInstaller
      run: pip install pyinstaller
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --clean -y --target-architecture x86_64 WovenSnips.spec
    
    - name: Create DMG
      run: |
        hdiutil create -volname WovenSnips -srcfolder dist/WovenSnips.app -ov -format UDZO WovenSnips.dmg
    
    - name: Upload DMG
      uses: actions/upload-artifact@v2
      with:
        name: WovenSnips-Intel
        path: WovenSnips.dmg
